### ISSUE TITLE
Writing to structs by pointer doesn't work?

### ISSUE THREAD

**Issue by burillo-se** [xlab/vorbis-go#3]
I'm trying to get ogg encoder to work. The encoding itself seems to work, but no data ever makes it out of the C structs. I think this might be a general problem with C-for-Go.

My code is basically a direct translation of vorbis encoder example into Go. When calling OggStreamFlush, the OggPage is passed to it, and, when the function returns a non-zero value, the page is expected to contain data written into it. However, that's not what happens.

Example here: https://github.com/burillo-se/ninjamencoder/blob/master/ninjamencoder.go#L184

```
		result := vorbis.OggStreamFlush(&streamState, &page)
		if result == 0 {
			break
		}
<...>
		fmt.Printf("Page contents: %v", page)
```
Output of the above code:
```Page contents: {[] 0 [] 0 0x7efc8c064660 0xc42000c320}```

So, the struct is modified by c-for-go to point to a C struct, but any changes happening to that struct made inside the C function, do not appear to be reflected in the Go struct. I can understand the empty slices (after all, C arrays don't have length, so c-for-go can't know that OggPage.HeaderLen is that array's length), but length doesn't make it out of the function and into the struct either.

**Comment by burillo-se** [comment]
It seems that one should call OggPage.Deref() after calling this function. Is there any reason why this is not done automatically? (if there is, then the need to call Deref() each time probably should be documented...)

**Comment by xlab** [comment]
@burillo-se hi, this is an automatically generated binding by [c-for-go](https://github.com/xlab/c-for-go), so it inherits all helpers that needed to pass the data back and forth.

Yes, the rule of thumb is that once the struct data on C side has been changed, it must be copied back to Go struct that acts like a view — using `.Deref()`.

> So, the struct is modified by c-for-go to point to a C struct, but any changes happening to that struct made inside the C function, do not appear to be reflected in the Go struct. 

Yep, the struct has a reference and the values that were copied.

>  Is there any reason why this is not done automatically? (if there is, then the need to call Deref() each time probably should be documented...)

Automatic dereference may have major performance and GC impact, sine it requires object allocation and copying. I left this to be manual, because this is a low-level binding. Low-level bindings are supposed to be used to build high-level abstractions, for example, a Decoder https://github.com/xlab/vorbis-go/blob/master/decoder/decoder.go

This Decoder hides all that logic from user, doing Derefs when needed.
